/*
 Copyright (C) 2019 SAS Institute Inc. Cary, NC, USA
*/

/**
   \file
   \brief   The report mart table CREDIT_RISK_DETAIL contains the required information for the SAS Visual Analytics Management Report
   \details

   | PK           |Variable                               |Type              | Required? |Relationships                                |Label                                       |Description                                                                                                                                                                                             |
   |--------------|---------------------------------------|------------------|-----------|---------------------------------------------|--------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
   |![ ](pk.jpg)  | ANALYSIS_RUN_ID                       | NUMERIC          | Y         | RGF Analysis Run Key                        | Analysis Run Id                            | Unique key of the Analysis Run that created the results                                                                                                                                                |
   |![ ](pk.jpg)  | WORKGROUP                             | CHARACTER(32)    | Y         |                                             | Workgroup                                  | SAS Risk Workgroup                                                                                                                                                                                     |
   |![ ](pk.jpg)  | LOAD_ID                               | CHARACTER(32)    | Y         |                                             | Load Id                                    | Identifies whether the current data was created as part of a production analysis run or not. \nValues: \n - Production \n - What-If                                                                    |
   |![ ](pk.jpg)  | <b>ENTITY_ID</b>                      | CHARACTER(32)    | N         | \link entity.sas \endlink                   | Entity Identifier                          | Entity Identifier                                                                                                                                                                                      |
   |![ ](pk.jpg)  | <b>REPORTING_DT</b>                   | NUMERIC(8)       | Y         |                                             | Reporting Date                             | Reference date for the calculation. Also known as the base date or evaluation date of the portfolio                                                                                                    |
   |![ ](pk.jpg)  | INSTID                                | CHARACTER(64)    | Y         |                                             | Instrument Identifier                      | Financial instrument identifier                                                                                                                                                                        |
   |![ ](pk.jpg)  | SCENARIO_ID                           | CHARACTER(32)    | Y         |                                             | Scenario Id                                | Unique scenario id used for the analysis. Each forecast time has a separate scenario id                                                                                                                |
   |![ ](pk.jpg)  | FORECAST_TIME                         | NUMERIC(8)       | N         |                                             | Forecast Time                              | Forecast time horizon                                                                                                                                                                                  |
   |![ ](pk.jpg)  | MOVEMENT_ID                           | NUMERIC(8)       | N         |                                             | Movement Id                                | Identifier for any changes that might occurr to the data as a result of a management adjustment/override. Model output has movement_id = 1, any adjustment is measured as a delta change from the previous movement_id, and stored using incremental movement_id values |
   |              | PROJECT_NAME                          | CHARACTER(64)    | Y         |                                             | Project Name                               | Name of the cycle in which the data was created                                                                                                                                                        |
   |              | ANALYSIS_RUN_NAME                     | CHARACTER(150)   | Y         |                                             | Analysis Run Name                          | Name of the analysis run that created this data                                                                                                                                                        |
   |              | ANALYSIS_TYPE_CD                      | CHARACTER(32)    | Y         |                                             | Analysis Type Code                         | Type of analysis run that created this data                                                                                                                                                            |   
   |              | SCENARIO_NAME                         | CHARACTER(512)   | Y         |                                             | Scenario Name                              | Name of the business scenario: it groups scenario id values across multiple forecast horizons                                                                                                          |
   |              | RULE_ID                               | CHARACTER(32)    | N         |                                             | Adjustment Rule Id                         | Adjustment Rule Id                                                                                                                                                                                     |     
   |              | RULE_DESC                             | CHARACTER(4096)  | N         |                                             | Adjustment Rule Description                | Adjustment Rule Description                                                                                                                                                                            |     
   |              | INSTTYPE                              | CHARACTER(32)    | N         |                                             | Instrument Type                            | Instrument type                                                                                                                                                                                        |
   |              | PORTFOLIO_SEGMENT                     | CHARACTER(50)    | N         |                                             | Portfolio Segment                          | Portfolio segmentation                                                                                                                                                                                 |
   |              | ACCOUNTING_TREATMENT_CD               | CHARACTER(32)    | N         |                                             | Accounting Treatment Code                  | Accounting Treatment also known as Carry Value Code.  Code used to categorize investments that are reported at amortized cost, Held to maturity securities (HTM), versus at fair value, Available for sale securities (AFS) |  
   |              | ACCOUNTING_METHOD                     | CHARACTER(14)    | N         |                                             | Accounting Method                          | Whether the instrument was evaluated at ammortized cost or at fair value                                                                                                                               |
   |              | ASSESSMENT_TYPE_CD                    | CHARACTER(10)    | N         |                                             | Assessment type Code                       | Assessment type code: <br> - IA <br> - CA                                                                                                                                                              |
   |              | ASSESSMENT_TYPE_DESC                  | CHARACTER(100)   | N         |                                             | Assessment type Description                | Assessment type description: <br> - Individual Assessment <br> - Collective Assessment                                                                                                                 |
   |              | ASSET_TYPE_DESC                       | CHARACTER(200)   | N         |                                             | Asset Type                                 | Asset type categorization                                                                                                                                                                              |
   |              | PRODUCT_CD                            | CHARACTER(200)   | N         | \link map_product_hierarchy.sas \endlink    | Product Code                               | Product Code                                                                                                                                                                                           |
   |              | PRODUCT_LEV1                          | CHARACTER(200)   | N         |                                             | Product Category                           | Product Category                                                                                                                                                                                       |
   |              | PRODUCT_LEV2                          | CHARACTER(200)   | N         |                                             | Product Sub-Category                       | Product Sub-Category                                                                                                                                                                                   |
   |              | PRODUCT_LEV3                          | CHARACTER(200)   | N         |                                             | Product Name                               | Product Name                                                                                                                                                                                           |
   |              | LOB_ID                                | CHARACTER(64)    | N         | \link map_lob_hierarchy.sas \endlink        | Line of Business Id                        | Line of Business Id (reporting dimension).                                                                                                                                                             |
   |              | LOB_LEV1                              | CHARACTER(200)   | N         |                                             | Line of Business Level 1                   | Line of Business Level 1 (reporting dimension).                                                                                                                                                        |
   |              | LOB_LEV2                              | CHARACTER(200)   | N         |                                             | Line of Business Level 2                   | Line of Business Level 2 (reporting dimension).                                                                                                                                                        |
   |              | LOB_LEV3                              | CHARACTER(200)   | N         |                                             | Line of Business Level 3                   | Line of Business Level 3 (reporting dimension).                                                                                                                                                        |
   |              | GEOGRAPHY_CD                          | CHARACTER(32)    | N         | \link map_geo_hierarchy.sas \endlink        | Geography Code                             | Geography Code (reporting dimension).                                                                                                                                                                  |
   |              | GEOGRAPHY_LEV1                        | CHARACTER(100)   | N         |                                             | Geography Level 1                          | Geography Level 1 (reporting dimension).                                                                                                                                                               |
   |              | GEOGRAPHY_LEV2                        | CHARACTER(100)   | N         |                                             | Geography Level 2                          | Geography Level 2 (reporting dimension).                                                                                                                                                               |
   |              | GEOGRAPHY_LEV3                        | CHARACTER(100)   | N         |                                             | Geography Level 3                          | Geography Level 3 (reporting dimension).                                                                                                                                                               |
   |              | GEOGRAPHY_LEV4                        | CHARACTER(100)   | N         |                                             | Geography Level 4                          | Geography Level 4 (reporting dimension).                                                                                                                                                               |
   |              | SECTOR_DESC                           | CHARACTER(100)   | N         |                                             | Sector Description                         | Sector Description                                                                                                                                                                                     |
   |              | CURRENCY                              | CHARACTER(3)     | N         |                                             | Currency                                   | Original currency                                                                                                                                                                                      |
   |              | ORIG_RATING_AGENCY                    | CHARACTER(32)    | N         |                                             | Rating Agency at Origination               | Credit Rating Agency (i.e. FICO, EQUIFAX, S&P)                                                                                                                                                         |
   |              | ORIG_RATING_GRADE                     | CHARACTER(32)    | N         |                                             | Rating Grade/Score at Origination          | Credit Rating Grade/Score. Example: 750 (FICO), AAA (S&P), etc.                                                                                                                                        |
   |              | ORIG_STD_RATING_GRADE                 | CHARACTER(32)    | N         |                                             | Standardised Rading Grade at Origination   | A standardized rating scale level is assigned to each loan (either retail or commercial) so that consistent reporting can be done across the entire portfolio. Mapping is required in order to assign a rating scale level to a given credit score (in case of retail) or rating grade (in case of commercial).<br>Closed List Values:<br> 1 - Largely Risk Free <br> - <i>2 - Minimal Risk</i> <br> - <i>3 - Modest Risk</i> <br> - <i>4 - Bankable</i> <br> - <i>5 - Additional Review</i> <br> - <i>6 - Special Mention</i> <br> - <i>7 - Sub-Standard</i> <br> - <i>8 - Doubtful</i> <br> - <i>9 - Loss</i>  |
   |              | ORIG_CREDIT_STATE                     | NUMERIC(8)       | N         |                                             | Credit State at Origination                | Numeric scale value corresponding to the value of column ORIG_STD_RATING_GRADE (range 1 to 9)                                                                                                          |
   |              | RATING_AGENCY                         | CHARACTER(32)    | N         |                                             | Rating Agency                              | Credit Rating Agency (i.e. FICO, EQUIFAX, S&P)                                                                                                                                                         |
   |              | RATING_GRADE                          | CHARACTER(32)    | N         |                                             | Rating Grade/Score                         | Credit Rating Grade/Score. Example: 750 (FICO), AAA (S&P), etc.                                                                                                                                        |
   |              | STD_RATING_GRADE                      | CHARACTER(32)    | N         |                                             | Standardised Rading Grade                  | A standardized rating scale level is assigned to each loan (either retail or commercial) so that consistent reporting can be done across the entire portfolio. Mapping is required in order to assign a rating scale level to a given credit score (in case of retail) or rating grade (in case of commercial).<br>Closed List Values:<br> 1 - Largely Risk Free <br> - <i>2 - Minimal Risk</i> <br> - <i>3 - Modest Risk</i> <br> - <i>4 - Bankable</i> <br> - <i>5 - Additional Review</i> <br> - <i>6 - Special Mention</i> <br> - <i>7 - Sub-Standard</i> <br> - <i>8 - Doubtful</i> <br> - <i>9 - Loss</i>  |
   |              | CREDIT_STATE                          | NUMERIC(8)       | N         |                                             | Credit State                               | Numeric scale value corresponding to the value of column STD_RATING_GRADE (range 1 to 9)                                                                                                               |
   |              | DRAWDOWN_PERIOD_FLG                   | CHARACTER(3)     | N         |                                             | Drawdown Period Flag                       | Indicates that a contract is in its drawdown period allowing additional drawdowns until the full CREDIT_LIMIT_AMT is reached and the OFF_BALANCE_AMT is 0.                                             |
   |              | ISSUED_GUARANTEE_FLG                  | CHARACTER(3)     | N         |                                             | Issued Flag                                | Indicates that a contract is a  pure off balance guarantee issued by the bank that can be called under certain conditions by a beneficiary.                                                            |
   |              | REVOLVING_FLG                         | CHARACTER(3)     | N         |                                             | Revolving Flag                             | Indicates that a contract is revolving, meaning that drawings and repayments don't follow a predefined schedule as long as the CREDIT_LIMIT_AMT is not exceeded.                                       |
   |              | DELINQUENCY_FLG                       | CHARACTER(3)     | N         |                                             | Delinquency Flag                           | Indicates delinquency (Y) or not (N)                                                                                                                                                                   |
   |              | EVER_DELINQUENT_FLG                   | CHARACTER(32)    | N         |                                             | Ever Delinquent Flag                       | Flag indicating whether there has ever been a delinquency                                                                                                                                              |
   |              | LOAN_STATUS_DESC                      | CHARACTER(32)    | N         |                                             | Loan Status                                | Status of the loan (for instance Impaired/Normal/Special Mention/Pipeline/Written-off...).                                                                                                             |
   |              | POCI_FLG                              | CHARACTER(3)     | N         |                                             | Purchased or Originated Credit Imparied Flag  | Identifies purchased financial assets with credit deterioration                                                                                                                                     |
   |              | TDR_FLG                               | CHARACTER(3)     | N         |                                             | Troubled Debt Restructuring Flag           | Identifies loans that are going through a debt restructuring due to economic or legal reasons related to a debtor's financial difficulties                                                             |
   |              | FORECLOSURE_FLG                       | CHARACTER(3)     | N         |                                             | Foreclosure Flag                           | Indicates a foreclosure action on the mortgage                                                                                                                                                         |
   |              | RELATED_PARTY_FLG                     | CHARACTER(3)     | N         |                                             | Related Party Flag                         | Identify related parties for disclosure (refer to FAS57)                                                                                                                                               |
   |              | COLLATERAL_SUPPORT_FLG                | CHARACTER(3)     | N         |                                             | Collateral Dependent Flag                  | Identify exposures with collaterals that can serve as alternative means of repayment when the counterparty is experiencing financial difficulties (ASU 2016-13 326-20-50-20)                           |
   |              | FINANCIAL_DIFFICULTIES_FLG            | CHARACTER(3)     | N         |                                             | Financial Difficulties Flag                | Identify counterparties that are experiencing financial difficulties (ASU 2016-13 326-20-50-20)                                                                                                        |
   |              | UNCONDITIONALLY_CANCELABLE_FLG        | CHARACTER(3)     | N         |                                             | Unconditionally Cancelable Flag            | Flag: Y/N. Identifies instruments for which a banking organization may, at any time, with or without cause, refuse to extend credit                                                                    |
   |              | DEACTIVATION_FLG                      | CHARACTER(3)     | N         |                                             | Deactivation Flag                          | Flag: Y/N. Identifies instruments that are eliminated from the original portfolio in a given activation scenario and horizon                                                                           |
   |              | SYNTHETIC_INSTRUMENT_FLG              | CHARACTER(3)     | N         |                                             | Synthetic Instrument Flag                  | Flag: Y/N. Identifies synthetic instruments that were generated based on the user business assumptions                                                                                                 |
   |              | ECL_STAGE                             | CHARACTER(10)    | Y         |                                             | ECL Stage Allocation                       | Stage Allocation. Valid values: <br> - Stage 1 <br> - Stage 2 <br> - Stage 3                                                                                                                           |
   |              | PREV_ECL_STAGE                        | CHARACTER(10)    | N         |                                             | Previous Period ECL Stage Allocation       | Previous Period Stage Allocation. Valid values: <br> - Stage 1 <br> - Stage 2 <br> - Stage 3                                                                                                           |
   |              | ACTIVATION_SCENARIO                   | CHARACTER(32)    | N         |                                             | Activation Scenario                        | The Scenario Id for which the synthetic instrument was generated and processed. Only relevant for synthetic instruments.                                                                               |
   |              | ACTIVATION_HORIZON                    | NUMERIC(8)       | N         |                                             | Activation Horizon                         | The time horizon in which the synthetic instrument becomes active (i.e. it is originated). For deactivated positions, this is the time horizon when the instrument is removed from the portfolio (i.e. short selling) |
   |              | ORIGINATION_DT                        | DATE             | N         |                                             | Origination Date                           | Loan start/origination date                                                                                                                                                                            |
   |              | MATURITY_DT                           | NUMERIC(8)       | N         |                                             | Maturity Date                              | Date on which the principal is fully paid off for the loan/security.                                                                                                                                   |   
   |              | ACQUISITION_DT                        | NUMERIC(8)       | N         |                                             | Acquisition Date                           | Date on which the loan or security was acquired is reported on the POCI Reconciliation disclosure template.                                                                                            |   
   |              | MOVEMENT_DESC                         | CHARACTER(100)   | N         |                                             | Movement Description                       | Custom description provided by the user when executing the adjustment allocation analysis. Used to provide a user specific comment about the change being applied on top of the model results          |
   |              | MOVEMENT_TYPE_CD                      | CHARACTER(32)    | N         |                                             | Movement Type Code                         | Movement type code. See \link map_movement_type.sas \endlink for a list of valid values                                                                                                                |
   |              | MOVEMENT_TYPE                         | CHARACTER(100)   | N         |                                             | Movement Type                              | Type of movement or adjustment. Looked up from \link map_movement_type.sas \endlink                                                                                                                    |
   |              | MOVEMENT_CATEGORY                     | CHARACTER(100)   | N         |                                             | Movement Category                          | Movement or Adjustment category. Looked up from \link map_movement_type.sas \endlink                                                                                                                   |
   |              | FORECAST_PERIOD                       | CHARACTER(32)    | N         |                                             | Forecast Period                            | Forecast Period expressed as the number of intervals from the Reporting Date. I.e. Year 0 (current period), Year 1, .., Year N                                                                         |
   |              | DAYS_PAST_DUE_CNT                     | NUMERIC(8)       | N         |                                             | Days Past Due                              | Number of days past the payment due date                                                                                                                                                               |
   |              | ORIG_UNPAID_BALANCE_AMT               | NUMERIC(8)       | N         |                                             | Unpaid Balance Amount at Origination       | Unpaid balance of the instrument at the origination dat e                                                                                                                                              |
   |              | ORIG_PIT_PD                           | NUMERIC(8)       | N         |                                             | PIT PD at Origination                      | Point-In-Time Probablilty of Default at origination                                                                                                                                                    |
   |              | ORIG_LTV_RT                           | NUMERIC(8)       | N         |                                             | LTV at Origination                         | Loan-To-Value Ratio at origination                                                                                                                                                                     |
   |              | PIT_PD                                | NUMERIC(8)       | N         |                                             | PIT PD                                     | Point-In-Time Probablilty of Default                                                                                                                                                                   |
   |              | LTV_RT                                | NUMERIC(8)       | N         |                                             | LTV                                        | Loan-to-Value expressed as a percentageof the collateral                                                                                                                                               |
   |              | LTV_DESC                              | CHARACTER(50)    | N         |                                             | LTV Description                            | Loan-to-Value description.  Looked up from \link map_ltv_type.sas \endlink                                                                                                                             |
   |              | LGD                                   | NUMERIC(8)       | N         |                                             | LGD                                        | Loss Given Default                                                                                                                                                                                     |
   |              | PD_12M                                | NUMERIC(8)       | N         |                                             | PD (12 months)                             | Probability of Default over the next 12 months                                                                                                                                                         |
   |              | PD_LIFETIME                           | NUMERIC(8)       | N         |                                             | PD (Lifetime)                              | Probability of Default over the lifetime of the loan                                                                                                                                                   |
   |              | LAPD                                  | NUMERIC(8)       | N         |                                             | Lifetime Annualized PD                     | Annualized value od the lifetime probability of default                                                                                                                                                |
   |              | LFPD                                  | NUMERIC(8)       | N         |                                             | Levelized Forward PD                       | Spread equivalent of the lifetime probability of default                                                                                                                                               |
   |              | CURRENT_RT                            | NUMERIC(8)       | N         |                                             | Current Rate                               | Decimal value                                                                                                                                                                                          |
   |              | EFFECTIVE_INTEREST_RT                 | NUMERIC(8)       | N         |                                             | Effective Interest Rate                    | Decimal value                                                                                                                                                                                          |
   |              | MARGIN_RT                             | NUMERIC(8)       | N         |                                             | Interest Rate Margin                       | Decimal value. Margin over the reference interest rate.                                                                                                                                                |
   |              | CREDIT_LIMIT_AMT                      | NUMERIC(8)       | N         |                                             | Credit Limit Amount                        | Indicates maximum allowed credit exposure on the contract.                                                                                                                                             |
   |              | UNPAID_BALANCE_AMT                    | NUMERIC(8)       | N         |                                             | Unpaid Balance Amount                      | Unpaid balance of the instrument at the reporting date                                                                                                                                                 |
   |              | DRAWN_PCT                             | NUMERIC(8)       | N         |                                             | Drawn Percentage                           | Drawn percentage for instruments with a nonzero credit limit                                                                                                                                           |
   |              | OFF_BALANCE_AMT                       | NUMERIC(8)       | N         |                                             | Off Balance Amount of the Contract         | Indicates amount of contract that is off balance, used for issued guarantees, revolving credits, pending credit offers and term loans in their drawdown period                                         |
   |              | WRITE_OFF_AMT                         | NUMERIC(8)       | N         |                                             | (Current Period) Write-off                 | Drives mapping to worksheets. See \ref p200Other "here" for general worksheet mapping information.       This is the current period write-off amount (partial or full)                                 |
   |              | CUM_WRITE_OFF_AMT                     | NUMERIC(8)       | N         |                                             | (Cumulative) Write-off                     | Drives mapping to worksheets. See \ref p200Other "here" for general worksheet mapping information.       This is the cumulative write-off amount (partial or full)                                     |   
   |              | PREV_CUM_WRITE_OFF_AMT                | NUMERIC(8)       | N         |                                             | (Cumulative - Previous Period) Write-off   | Cumulative write-off amount from the previous period.                                                                                                                                                  |   
   |              | RECOVERY_AMT                          | NUMERIC(8)       | N         |                                             | (Current Period) Recovery Amount           | Drives mapping to worksheets. See \ref p200Other "here" for general worksheet mapping information.       This is the current period recovery amount (partial or full)                                  |
   |              | CUM_RECOVERY_AMT                      | NUMERIC(8)       | N         |                                             | (Cumulative) Recovery Amount               | Drives mapping to worksheets. See \ref p200Other "here" for general worksheet mapping information.       This is the cumulative recovery amount (partial or full)                                      |   
   |              | PREV_CUM_RECOVERY_AMT                 | NUMERIC(8)       | N         |                                             | (Cumulative - Previous Period) Recovery Amount | Cumulative recovery amount from the previous period.                                                                                                                                               |   
   |              | FEE_AMT                               | NUMERIC(8)       | N         |                                             | Amount of Fees                             | Collected fees                                                                                                                                                                                         |
   |              | ACCRUED_INTEREST_AMT                  | NUMERIC(8)       | N         |                                             | Accrued Interest                           | Accrued Interest                                                                                                                                                                                       |
   |              | POCI_PURCHASE_AMT                     | NUMERIC(8)       | N         |                                             | POCI Purchase Amount                       | Purchase price of POCI assets is reported on POCI Reconciliation disclosure template.                                                                                                                  |
   |              | ECL_12M                               | NUMERIC(8)       | N         |                                             | ECL (12 months)                            | Expected Credit Loss over the next 12 months                                                                                                                                                           |
   |              | ECL_LIFETIME                          | NUMERIC(8)       | N         |                                             | ECL (Lifetime)                             | Expected Credit Loss over the lifetime of the loan                                                                                                                                                     |
   |              | ECL                                   | NUMERIC(8)       | Y         |                                             | ECL (Staged)                               | Staged Expected Credit Loss                                                                                                                                                                            |
   |              | PREV_ECL                              | NUMERIC(8)       | N         |                                             | Previous Period ECL                        | Staged Previous Period Expected Credit Loss                                                                                                                                                            |
   |              | COLLATERAL_TYPE                       | NUMERIC(8)       | N         |                                             | Collateral Type                            | Collateral Type                                                                                                                                                                                        |  
   |              | COUNTERPARTY_TYPE                     | VARCHAR(100)     | N         |                                             | Counterparty Type                          | Counterparty Type                                                                                                                                                                                      |
   |              | POCI_PAR_AMT                          | NUMERIC(8)       | N         |                                             | POCI Par Value Amount                      | POCI Par Value Amount                                                                                                                                                                                  |
   |              | COLLATERAL_VALUE_AMT                  | NUMERIC(8)       | N         |                                             | Collateral Value Amount                    | Collateral Value Amount                                                                                                                                                                                |  
   |              | AMORTIZED_COST_AMT                    | NUMERIC(8)       | N         |                                             | Amortized Cost Basis Amount                | Amortized Cost Basis Amount                                                                                                                                                                            |  
   |              | NET_WRITE_OFF_AMT                     | NUMERIC(8)       | N         |                                             | Net Write Off Amount                       | Net write off amount.                                                                                                                                                                                  |  
   |              | PROVISION_EXPENSE_AMT                 | NUMERIC(8)       | N         |                                             | Provision Expense Amount                   | Provision expense amount.                                                                                                                                                                              |  
   |              | FAIR_VALUE                            | NUMERIC          | N         |                                             | Fair Value                                 | Also know as Market Value.  The estimated price at which an asset can be sold or a liability settled in an orderly transaction to a third party under current market conditions.                       |
   |              | ACQUISITION_DT                        | DATE             | N         |                                             | Purchase Date                              | The date on which the financial instruments was acquired.                                                                                                                                              |
   |              | ACQUISITION_PRICE                     | NUMERIC          | N         |                                             | Acquisition Price per unit                 | The unit price paid per unit of holding to acquire a financial asset.                                                                                                                                  |
   |              | ISSUANCE_DATE                         | DATE             | N         |                                             | Issuance Date                              | The date on which a company or government makes a new issue of securities to the public.                                                                                                               |
   |              | ISSUER_NAME                           | VARCHAR(100)     | N         |                                             | Issuer Name                                | The name of legal entity that develops, registers and sells securities for the purpose of financing its operations. Issuers may be domestic or foreign governments, corporations or investment trusts. |
   |              | POCI_PURCHASE_DT                      | NUMERIC(8)       | N         |                                             | POCI Purchase Date                          | Used to determine if a POCI asset was purchased in the current reporting period.                                                                                                                      |
   |              | NONACCRUAL_STATUS_FLG                 | VARCHAR(3)       | N         |                                             | Nonaccrual Status Flag                     | Indicates nonaccrual status (Y) or not (N)                                                                                                                                                             |
   |              | DPD_CLASS                             | VARCHAR(50)      | N         |                                             | Days Past Due Classification               | Days Past Due Classification used in the Disclosure Past Due Reports                                                                                                                                   |
   |              | INTEREST_INCOME_ON_NON_ACC_AMT        | NUMERIC(8)       | N         |                                             | Interest Income Amount on Nonaccrual       | Interest income recognized during the period on nonaccrual assets is reported on nonaccrual disclosure template.                                                                                       |
   |              | NOMINAL_AMT                           | NUMERIC(8)       | N         |                                             | Nominal Amount                             | Nominal Amount = OFF_BALANCE_AMT + UNPAID_BALANCE_AMT                                                                                                                                                  |
   |              | ALLOWANCE_AMT                         | NUMERIC(8)       | N         |                                             | Allowance Amount                           | Allowance Amount                                                                                                                                                                                       |     
   |              | PREV_ALLOWANCE_AMT                    | NUMERIC(8)       | N         |                                             | Previous Period Allowance Amount           | Previous Period Allowance Amount                                                                                                                                                                       |     
   |              | PARTIAL_WRITE_OFF_AMT                 | NUMERIC(8)       | N         |                                             | Partial Write Off Amount                   | Partial Write Off Amount                                                                                                                                                                               |      
   |              | FINREP_NON_PERFORMING_FLG             | CHARACTER(1)     | N         |                                             | Finrep - Non-performing indicator          | FINREP non-performing indicator                                                                                                                                                                        |
   |              | FINREP_COLLATERAL_TYPE                | CHARACTER(64)    | N         |                                             | Finrep - Collateral Type                   | FINREP collateral type                                                                                                                                                                                 |
   |              | FINREP_PURPOSE_TYPE                   | CHARACTER(32)    | N         |                                             | Finrep - Purpose Type Code                 | FINREP purpose type code                                                                                                                                                                               |
   |              | FINREP_PROJECT_FINANCE_FLG            | CHARACTER(1)     | N         |                                             | Finrep - Project Finance indicator         | Accepts either Y (yes) or N (no). Drives mapping to FINREP templates                                                                                                                                   |
   |              | LOW_CREDIT_RISK_FLG                   | CHARACTER(1)     | N         |                                             | Low Credit Risk Flag                       | Accepts either Y (yes) or N (no). Indicates whether the instrument is subject to low credit risk as referred to by IFRS9 B.5.2.22-B.5.2.24. Note that alternatively this flag can be derived in the stage allocation logic.  |
   |              | IRRECOVERABLE_FLG                     | CHARACTER(1)     | N         |                                             | Finrep - Irrecoverable contract flag       | Drives mapping to FINREP templates.  Used together with write-off amount to identify amounts to be reported on write-offs.                                                                             |
   |              | MODIFIED_FLG                          | CHARACTER(1)     | N         |                                             | Modification flag                          | Indicates modification of the instrument. Used in FINREP 12.1 report for "Changes due to change in credit risk (net)" and "Changes due to modifications without derecognition (net)"                   |
   |              | SPPI_PRODUCT_TYPE_CD                  | CHARACTER(20)    | N         |                                             | SPPI Product Type                          |                                                                                                                                                                                                        |
   |              | SPPI_PRODUCT_SUBTYPE_CD               | CHARACTER(20)    | N         |                                             | SPPI Product Sub Type                      |                                                                                                                                                                                                        |
   |              | NON_RECOURSE_PROVISION_FLG            | CHARACTER(1)     | N         |                                             | Non Recourse Provision Flag                | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | MATURITY_CAP_INT_FLG                  | CHARACTER(1)     | N         |                                             | Maturity Cap Int Flag                      | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | DEFERRAL_POSSIBLE_FLG                 | CHARACTER(1)     | N         |                                             | Deferral Possible Flag                     | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | INT_COMPOUNDING_FLG                   | CHARACTER(1)     | N         |                                             | Interest Compounding Flag                  | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | LOSSES_TO_HOLDER_FLG                  | CHARACTER(1)     | N         |                                             | Losses to Holder Flag                      | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | INTEREST_BASE_OUTSTANDING_FLG         | CHARACTER(1)     | N         |                                             | Interest Base Outstanding Flag             | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | INTEREST_PAYM_CANCELLABLE_FLG         | CHARACTER(1)     | N         |                                             | Interest Payment Cancellable Flag          | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | INTEREST_PAYM_DEFERRABLE_FLG          | CHARACTER(1)     | N         |                                             | Interest Payment Deferrable Flag           | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | DEFERRED_INT_PMNT_ACCRUE_FLG          | CHARACTER(1)     | N         |                                             | Deferred Interest Payment Accrue Flag      | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | CF_INDEXED_FLG                        | CHARACTER(1)     | N         |                                             | Cashflow Indexed Flag                      | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | ZERO_CURVE_REF                        | CHARACTER(32)    | N         |                                             | Zero Curve Reference                       | Defaults to NA when not relevant, else must be a risk factor curve                                                                                                                                     |
   |              | INVERSE_FLOATING_FLG                  | CHARACTER(1)     | N         |                                             | Inverse Floating Flag                      | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | FINANCIAL_LEVERAGE_FLG                | CHARACTER(1)     | N         |                                             | Financial Leverage Flag                    | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | INTEREST_EXT_FIXED_FLG                | CHARACTER(1)     | N         |                                             | Interest Ext Fixed Flag                    | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | INTEREST_EXT_FIXED_COM_FLG            | CHARACTER(1)     | N         |                                             | Interest Ext Fixed Com Flag                | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | PREPAYMENT_POSSIBLE_FLG               | CHARACTER(1)     | N         |                                             | Prepayment Possible Flag                   | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | PREPAYMENT_AMT_CAP_INT_FLG            | CHARACTER(1)     | N         |                                             | Prepayment Amount Cap Int Flag             | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | ORIGINATED_PREM_DISCOUNT_FLG          | CHARACTER(1)     | N         |                                             | Originated Prem Discount Flag              | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | SIGNIFICANT_AMT_FLG                   | CHARACTER(1)     | N         |                                             | Significant Amount Flag                    | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | MATURITY_EXT_POSSIBLE_FLG             | CHARACTER(1)     | N         |                                             | Maturity Ext Possible Flag                 | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | INT_MARKET_RATE_FLG                   | CHARACTER(1)     | N         |                                             | Interest Market Rate Flag                  | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | MATURITY_EXT_CAP_INT_FLG              | CHARACTER(1)     | N         |                                             | Maturity Ext Cap Int Flag                  | Accepts either Y (yes) or N (no)                                                                                                                                                                       |
   |              | SPPI_TEST                             | CHARACTER(15)    | N         |                                             | SPPI Test Result                           | SPPI Test Pass (PASSED) or Fail (FAILED).                                                                                                                                                              |    
    
   \ingroup ddlReportMart
   \author  SAS Institute Inc.
   \date    2019
*/

create table &libref..CREDIT_RISK_DETAIL (
   ANALYSIS_RUN_ID                  NUMERIC        label = "Analysis Run Id",
   ANALYSIS_RUN_NAME                VARCHAR(150)   label = "Analysis Run Name",
   ANALYSIS_TYPE_CD                 VARCHAR(32)    label = "Analysis Type Code",
   LOAD_ID                          VARCHAR(32)    label = "Load Id",
   REPORTING_DT                     DATE           label = "Reporting Date"                                 FORMAT = yymmddd10.,
   ENTITY_ID                        VARCHAR(32)    label = "Entity",
   WORKGROUP                        VARCHAR(32)    label = "Workgroup",
   PROJECT_NAME                     VARCHAR(64)    label = "Project Name",
   SCENARIO_ID                      VARCHAR(32)    label = 'Scenario Id',
   SCENARIO_NAME                    VARCHAR(512)   label = 'Scenario Name',
   RULE_ID                          VARCHAR(32)    label = 'Adjustment Rule Id',
   RULE_DESC                        VARCHAR(4096)  label = 'Adjustment Rule Description',
   INSTID                           VARCHAR(64)    label = 'Instrument Identifier',
   INSTTYPE                         VARCHAR(32)    label = 'Instrument Type',
   PORTFOLIO_SEGMENT                VARCHAR(50)    label = 'Portfolio Segment',
   ACCOUNTING_TREATMENT_CD          VARCHAR(32)    label = 'Accounting Treatment Code',
   ACCOUNTING_METHOD                VARCHAR(14)    label = 'Accounting Method',
   ASSESSMENT_TYPE_CD               VARCHAR(10)    label = 'Assessment Type Code',
   ASSESSMENT_TYPE_DESC             VARCHAR(100)   label = 'Assessment Type Description',
   ASSET_TYPE_DESC                  VARCHAR(200)   label = 'Asset Type',
   PRODUCT_CD                       VARCHAR(100)   label = 'Product Code',
   PRODUCT_LEV1                     VARCHAR(200)   label = 'Product Category',
   PRODUCT_LEV2                     VARCHAR(200)   label = 'Product Sub-Category',
   PRODUCT_LEV3                     VARCHAR(200)   label = 'Product Name',
   LOB_ID                           VARCHAR(100)   label = 'Line of Business Id',
   LOB_LEV1                         VARCHAR(200)   label = 'Line of Business Level 1',
   LOB_LEV2                         VARCHAR(200)   label = 'Line of Business Level 2',
   LOB_LEV3                         VARCHAR(200)   label = 'Line of Business Level 3',
   GEOGRAPHY_CD                     VARCHAR(32)    label = 'Geography Code',
   GEOGRAPHY_LEV1                   VARCHAR(100)   label = "Geography Level 1",
   GEOGRAPHY_LEV2                   VARCHAR(100)   label = "Geography Level 2",
   GEOGRAPHY_LEV3                   VARCHAR(100)   label = "Geography Level 3",
   GEOGRAPHY_LEV4                   VARCHAR(100)   label = "Geography Level 4",
   SECTOR_DESC                      VARCHAR(100)   label = 'Sector Description',   
   CURRENCY                         VARCHAR(3)     label = 'Currency',
   ORIG_RATING_AGENCY               VARCHAR(32)    label = 'Rating Agency at Origination',
   ORIG_RATING_GRADE                VARCHAR(32)    label = 'Rating Grade at Origination',
   ORIG_STD_RATING_GRADE            VARCHAR(32)    label = 'Standardised Rating Grade at Origination',
   ORIG_CREDIT_STATE                NUMERIC(8)     label = 'Credit State at Origination',
   RATING_AGENCY                    VARCHAR(32)    label = 'Rating Agency',
   RATING_GRADE                     VARCHAR(32)    label = 'Rating Grade',
   STD_RATING_GRADE                 VARCHAR(32)    label = 'Standardised Rating Grade',
   CREDIT_STATE                     NUMERIC(8)     label = 'Credit State',
   DRAWDOWN_PERIOD_FLG              VARCHAR(3)     label = 'Drawdown Period Flag',
   ISSUED_GUARANTEE_FLG             VARCHAR(3)     label = 'Issued Guarantee Flag',
   REVOLVING_FLG                    VARCHAR(3)     label = 'Revolving Flag',
   DELINQUENCY_FLG                  VARCHAR(3)     label = 'Delinquency Flag',
   EVER_DELINQUENT_FLG              VARCHAR(3)     label = 'Ever Delinquent Flag',
   LOAN_STATUS_DESC                 VARCHAR(32)    label = 'Loan Status',
   POCI_FLG                         VARCHAR(3)     label = 'Purchased or Originated Credit Imparied Flag',
   TDR_FLG                          VARCHAR(3)     label = 'Troubled Debt Restructuring Flag',
   FORECLOSURE_FLG                  VARCHAR(3)     label = 'Foreclosure Flag',
   RELATED_PARTY_FLG                VARCHAR(3)     label = 'Related Party Flag',
   COLLATERAL_SUPPORT_FLG           VARCHAR(3)     label = 'Collateral Support Flag',
   FINANCIAL_DIFFICULTIES_FLG       VARCHAR(3)     label = 'Financial Difficulties Flag',
   UNCONDITIONALLY_CANCELABLE_FLG   VARCHAR(3)     label = 'Unconditionally Cancelable Flag',
   DEACTIVATION_FLG                 VARCHAR(3)     label = 'Deactivation Flag',
   SYNTHETIC_INSTRUMENT_FLG         VARCHAR(3)     label = 'Synthetic Instrument Flag',
   ECL_STAGE                        VARCHAR(10)    label = 'ECL Stage Allocation',
   PREV_ECL_STAGE                   VARCHAR(10)    label = 'Previous Period ECL Stage Allocation',
   ACTIVATION_SCENARIO              VARCHAR(32)    label = 'Activation Scenario',
   ACTIVATION_HORIZON               NUMERIC(8)     label = 'Activation Horizon',
   ORIGINATION_DT                   DATE           label = 'Origination Date'                               FORMAT = yymmddd10.,
   MATURITY_DT                      DATE           label = 'Maturity Date'                                  FORMAT = yymmddd10.,
   ACQUISITION_DT                   NUMERIC(8)     label = 'Acquisition Date'                               FORMAT = yymmddd10.,
   MOVEMENT_ID                      NUMERIC(8)     label = 'Movement Id',
   MOVEMENT_DESC                    VARCHAR(100)   label = 'Movement Description',
   MOVEMENT_TYPE_CD                 VARCHAR(32)    label = 'Movement Type Code',
   MOVEMENT_TYPE                    VARCHAR(100)   label = 'Movement Type',
   MOVEMENT_CATEGORY                VARCHAR(100)   label = 'Movement Category',
   FORECAST_PERIOD                  VARCHAR(32)    label = 'Forecast Period',
   FORECAST_TIME                    NUMERIC(8)     label = 'Forecast Time',
   DAYS_PAST_DUE_CNT                NUMERIC(8)     label = 'Days Past Due',
   ORIG_UNPAID_BALANCE_AMT          NUMERIC(8)     label = 'Unpaid Balance Amount at Origination'           FORMAT = comma25.2,
   ORIG_PIT_PD                      NUMERIC(8)     label = 'PIT PD at Origination'                          FORMAT = percent8.2,
   ORIG_LTV_RT                      NUMERIC(8)     label = 'LTV at Origination'                             FORMAT = percent8.2,
   PIT_PD                           NUMERIC(8)     label = 'PIT PD'                                         FORMAT = percent8.2,
   LTV_RT                           NUMERIC(8)     label = 'LTV'                                            FORMAT = percent8.2,
   LTV_DESC                         VARCHAR(50)    label = 'LTV Type',
   LGD                              NUMERIC(8)     label = 'LGD'                                            FORMAT = percent8.2,
   PD_12M                           NUMERIC(8)     label = 'PD 12 Month'                                    FORMAT = percent8.2,
   PD_LIFETIME                      NUMERIC(8)     label = 'PD (Lifetime)'                                  FORMAT = percent8.2,
   LAPD                             NUMERIC(8)     label = 'Lifetime Annualized PD'                         FORMAT = percent8.2,
   LFPD                             NUMERIC(8)     label = 'Levelized Forward PD'                           FORMAT = percent8.2,
   CURRENT_RT                       NUMERIC(8)     label = 'Current Contractual Interest Rate'              FORMAT = percent8.2,
   EFFECTIVE_INTEREST_RT            NUMERIC(8)     label = 'Effective Interest Rate'                        FORMAT = percent8.2,
   MARGIN_RT                        NUMERIC(8)     label = 'Interest Rate Margin'                           FORMAT = percent8.2,
   CREDIT_LIMIT_AMT                 NUMERIC(8)     label = 'Credit Limit Amount'                            FORMAT = comma25.2,
   UNPAID_BALANCE_AMT               NUMERIC(8)     label = 'Unpaid Balance Amount'                          FORMAT = comma25.2,
   DRAWN_PCT                        NUMERIC(8)     label = 'Drawn Percentage'                               FORMAT = percent8.2,
   OFF_BALANCE_AMT                  NUMERIC(8)     label = 'Off-Balance Amount'                             FORMAT = comma25.2,
   WRITE_OFF_AMT                    NUMERIC(8)     label = 'Current Period Write-off Amount'                FORMAT = comma25.2,
   CUM_WRITE_OFF_AMT                NUMERIC(8)     label = 'Cumulative Write-off Amount'                    FORMAT = comma25.2,
   PREV_CUM_WRITE_OFF_AMT           NUMERIC(8)     label = 'Previous Period Cumulative Write-off Amount'    FORMAT = comma25.2,
   RECOVERY_AMT                     NUMERIC(8)     label = 'Current Period Recovery Amount'                 FORMAT = comma25.2,
   CUM_RECOVERY_AMT                 NUMERIC(8)     label = 'Cumulative Recovery Amount'                     FORMAT = comma25.2,
   PREV_CUM_RECOVERY_AMT            NUMERIC(8)     label = 'Previous Period Cumulative Recovery Amount'     FORMAT = comma25.2,
   FEE_AMT                          NUMERIC(8)     label = 'Amount of Fees'                                 FORMAT = comma25.2,
   ACCRUED_INTEREST_AMT             NUMERIC(8)     label = 'Accrued Interest'                               FORMAT = comma25.2,
   POCI_PURCHASE_AMT                NUMERIC(8)     label = 'POCI Purchase Amount'                           FORMAT = comma25.2,
   ECL_12M                          NUMERIC(8)     label = 'ECL (12 Months)'                                FORMAT = comma25.2,
   ECL_LIFETIME                     NUMERIC(8)     label = 'ECL (Lifetime)'                                 FORMAT = comma25.2,
   ECL                              NUMERIC(8)     label = 'ECL (Staged)'                                   FORMAT = comma25.2,
   PREV_ECL                         NUMERIC(8)     label = 'Previous Period ECL'                            FORMAT = comma25.2,
   COLLATERAL_TYPE                  VARCHAR(100)   label = 'Collateral Type',
   COUNTERPARTY_TYPE                VARCHAR(100)   label = 'Counterparty Type',
   POCI_PAR_AMT                     NUMERIC(8)     label = 'POCI Par Value Amount'                          FORMAT = comma25.2,
   COLLATERAL_VALUE_AMT             NUMERIC(8)     label = 'Collateral Value Amount'                        FORMAT = comma25.2,
   AMORTIZED_COST_AMT               NUMERIC(8)     label = 'Amortized Cost Basis Amount'                    FORMAT = comma25.2,
   NET_WRITE_OFF_AMT                NUMERIC(8)     label = 'Net Write Off Amount'                           FORMAT = comma25.2,
   PROVISION_EXPENSE_AMT            NUMERIC(8)     label = 'Provision Expense Amount'                       FORMAT = comma25.2,
   FAIR_VALUE                       NUMERIC        label = 'Fair Value'                                     FORMAT = comma25.2,
   ACQUISITION_DT                   DATE           label = 'Purchase Date'                                  FORMAT = yymmddd10.,
   ACQUISITION_PRICE                NUMERIC        label = 'Acquisition Price per unit'                     FORMAT = comma25.2,
   ISSUANCE_DATE                    DATE           label = 'Issuance Date'                                  FORMAT = yymmddd10.,
   ISSUER_NAME                      VARCHAR(100)   label = 'Issuer Name',
   POCI_PURCHASE_DT                 NUMERIC(8)     label = 'POCI Purchase Date'                             FORMAT = yymmddd10.,
   UNREALIZED_LOSS_THRU_INC_STMT    NUMERIC        label = 'Unrealized Loss (Through Income Statement)'     FORMAT = comma25.2,
   NONACCRUAL_STATUS_FLG            VARCHAR(3)     label = 'Nonaccrual Status Flag',
   DPD_CLASS                        VARCHAR(50)    label = 'Days Pass Due Classification',
   INTEREST_INCOME_ON_NON_ACC_AMT   NUMERIC(8)     label = 'Interest Income Amount on Nonaccrual',
   NOMINAL_AMT                      NUMERIC(8)     label = 'Nominal Amount',
   ALLOWANCE_AMT                    NUMERIC(8)     label = 'Allowance Amount'                               FORMAT = comma25.2,
   PREV_ALLOWANCE_AMT               NUMERIC(8)     label = 'Previous Period Allowance Amount'               FORMAT = comma25.2,
   PARTIAL_WRITE_OFF_AMT            NUMERIC(8)     label = 'Partial Write Off Amount'                       FORMAT = comma25.2,
   FINREP_NON_PERFORMING_FLG        VARCHAR(1)     label = 'Finrep - Non-performing indicator',
   FINREP_COLLATERAL_TYPE           VARCHAR(64)    label = 'Finrep - Collateral Type',
   FINREP_PURPOSE_TYPE              VARCHAR(32)    label = 'Finrep - Purpose Type',
   FINREP_PROJECT_FINANCE_FLG       VARCHAR(1)     label = 'Finrep - Project Finance indicator',
   LOW_CREDIT_RISK_FLG              VARCHAR(1)     label = 'Low Credit Risk Flag',
   IRRECOVERABLE_FLG                VARCHAR(1)     label = 'Finrep - Irrecoverable contract flag',
   MODIFIED_FLG                     VARCHAR(1)     label = 'Modification Flag',
   SPPI_PRODUCT_TYPE_CD             VARCHAR(20)    label = 'SPPI Product Type',
   SPPI_PRODUCT_SUBTYPE_CD          VARCHAR(20)    label = 'SPPI Product Sub Type',
   NON_RECOURSE_PROVISION_FLG       VARCHAR(1)     label = 'Non Recourse Provision Flag',
   MATURITY_CAP_INT_FLG             VARCHAR(1)     label = 'Maturity Cap Int Flag',
   DEFERRAL_POSSIBLE_FLG            VARCHAR(1)     label = 'Deferral Possible Flag',
   INT_COMPOUNDING_FLG              VARCHAR(1)     label = 'Interest Compounding Flag',
   LOSSES_TO_HOLDER_FLG             VARCHAR(1)     label = 'Losses to Holder Flag',
   INTEREST_BASE_OUTSTANDING_FLG    VARCHAR(1)     label = 'Interest Base Outstanding Flag',
   INTEREST_PAYM_CANCELLABLE_FLG    VARCHAR(1)     label = 'Interest Payment Cancellable Flag',
   INTEREST_PAYM_DEFERRABLE_FLG     VARCHAR(1)     label = 'Interest Payment Deferrable Flag',
   DEFERRED_INT_PMNT_ACCRUE_FLG     VARCHAR(1)     label = 'Deferred Interest Payment Accrue Flag',
   CF_INDEXED_FLG                   VARCHAR(1)     label = 'Cashflow Indexed Flag',
   ZERO_CURVE_REF                   VARCHAR(32)    label = 'Zero Curve Reference',
   INVERSE_FLOATING_FLG             VARCHAR(1)     label = 'Inverse Floating Flag',
   FINANCIAL_LEVERAGE_FLG           VARCHAR(1)     label = 'Financial Leverage Flag',
   INTEREST_EXT_FIXED_FLG           VARCHAR(1)     label = 'Interest Ext Fixed Flag',
   INTEREST_EXT_FIXED_COM_FLG       VARCHAR(1)     label = 'Interest Ext Fixed Com Flag',
   PREPAYMENT_POSSIBLE_FLG          VARCHAR(1)     label = 'Prepayment Possible Flag',
   PREPAYMENT_AMT_CAP_INT_FLG       VARCHAR(1)     label = 'Prepayment Amount Cap Int Flag',
   ORIGINATED_PREM_DISCOUNT_FLG     VARCHAR(1)     label = 'Originated Prem Discount Flag',
   SIGNIFICANT_AMT_FLG              VARCHAR(1)     label = 'Significant Amount Flag',
   MATURITY_EXT_POSSIBLE_FLG        VARCHAR(1)     label = 'Maturity Ext Possible Flag',
   INT_MARKET_RATE_FLG              VARCHAR(1)     label = 'Interest Market Rate Flag',
   MATURITY_EXT_CAP_INT_FLG         VARCHAR(1)     label = 'Maturity Ext Cap Int Flag',
   SPPI_TEST                        VARCHAR(15)    label = 'SPPI Test Result'
    
);

