/* Copyright (C) 2018 SAS Institute Inc. Cary, NC, USA */

/*!
   \file
   \brief   Sample data for VAR_DEPENDENCY_CONFIG.

   \details Sample data for VAR_DEPENDENCY_CONFIG. For documentation and guidance please refer to the corresponding ddl file.

   \ingroup sampledata
   \author  SAS Institute Inc.
   \date    2018
*/

data WORK.var_dependency_config;
   attrib
      SCHEMA_NAME          length = $150.
      SCHEMA_VERSION       length = $50.
      TRIGGER_VAR_NAME     length = $32.
      ORDER_NO             length = 8.
      DEPENDENT_VAR_NAME   length = $32.
      EXPRESSION_TXT       length = $4096.
   ;
   infile cards dsd delimiter = ',';
   input
      SCHEMA_NAME          :$char.
      SCHEMA_VERSION       :$char.
      TRIGGER_VAR_NAME     :$char.
      ORDER_NO
      DEPENDENT_VAR_NAME   :$char.
      EXPRESSION_TXT       :$char.
   ;
   if(symexist("content_version")) then
      SCHEMA_VERSION = resolve(SCHEMA_VERSION);
datalines4;
IFRS9_CREDIT_RISK_DETAIL,&content_version.,CUM_WRITE_OFF_AMT,1,WRITE_OFF_AMT,"sum(CUM_WRITE_OFF_AMT, -PREV_CUM_WRITE_OFF_AMT)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,CUM_RECOVERY_AMT,1,RECOVERY_AMT,"sum(CUM_RECOVERY_AMT, -PREV_CUM_RECOVERY_AMT)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,CUM_WRITE_OFF_AMT,2,NET_WRITE_OFF_AMT,"sum(WRITE_OFF_AMT, -RECOVERY_AMT)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,CUM_RECOVERY_AMT,2,NET_WRITE_OFF_AMT,"sum(WRITE_OFF_AMT, -RECOVERY_AMT)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,ECL_12M,1,ECL,"ifn(ECL_STAGE = 'Stage 1', ECL_12M, ECL_LIFETIME)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,ECL_12M,2,PROVISION_EXPENSE_AMT,"sum(ECL, -PREV_ECL)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,ECL_LIFETIME,1,ECL,"ifn(ECL_STAGE = 'Stage 1', ECL_12M, ECL_LIFETIME)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,ECL_LIFETIME,2,PROVISION_EXPENSE_AMT,"sum(ECL, -PREV_ECL)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,ECL,1,PROVISION_EXPENSE_AMT,"sum(ECL, -PREV_ECL)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,UNPAID_BALANCE_AMT,1,DRAWN_PCT,"divide(UNPAID_BALANCE_AMT, CREDIT_LIMIT_AMT)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,CREDIT_LIMIT_AMT,1,DRAWN_PCT,"divide(UNPAID_BALANCE_AMT, CREDIT_LIMIT_AMT)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,ECL_LIFETIME,4,ALLOWANCE_AMT,"sum(PREV_ALLOWANCE_AMT, PROVISION_EXPENSE_AMT, RECOVERY_AMT, -WRITE_OFF_AMT, 0)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,ECL_12M,4,ALLOWANCE_AMT,"sum(PREV_ALLOWANCE_AMT, PROVISION_EXPENSE_AMT, RECOVERY_AMT, -WRITE_OFF_AMT, 0)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,ECL,4,ALLOWANCE_AMT,"sum(PREV_ALLOWANCE_AMT, PROVISION_EXPENSE_AMT, RECOVERY_AMT, -WRITE_OFF_AMT, 0)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,PROVISION_EXPENSE_AMT,4,ALLOWANCE_AMT,"sum(PREV_ALLOWANCE_AMT, PROVISION_EXPENSE_AMT, RECOVERY_AMT, -WRITE_OFF_AMT, 0)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,CUM_RECOVERY_AMT,4,ALLOWANCE_AMT,"sum(PREV_ALLOWANCE_AMT, PROVISION_EXPENSE_AMT, RECOVERY_AMT, -WRITE_OFF_AMT, 0)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,CUM_WRITE_OFF_AMT,4,ALLOWANCE_AMT,"sum(PREV_ALLOWANCE_AMT, PROVISION_EXPENSE_AMT, RECOVERY_AMT, -WRITE_OFF_AMT, 0)"
IFRS9_CREDIT_RISK_DETAIL,&content_version.,PARTIAL_WRITE_OFF_AMT,1,CUM_WRITE_OFF_AMT,"ifn(round(CUM_WRITE_OFF_AMT)^=round(UNPAID_BALANCE_AMT) and IRRECOVERABLE_FLG='N',CUM_WRITE_OFF_AMT,0)"
;;;;
run;
