
/*
 Copyright (C) 2018 SAS Institute Inc. Cary, NC, USA
*/
 
/**
   \file
   \brief   Credit risk portfolio table.
   \details
 
   |PK            |Variable                               |Type              | Required? |Relationships                                   |Label                                       |Description                                                                                                                                                                                             |
   |--------------|---------------------------------------|------------------|-----------|------------------------------------------------|--------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
   |![ ](pk.jpg)  | <b>REPORTING_DT</b>                   | NUMERIC(8)       | Y         |                                                | Reporting Date                             | SAS Date value                                                                                                                                                                                         |
   |![ ](pk.jpg)  | <b>ENTITY_ID</b>                      | CHARACTER(32)    | N         | \link entity.sas \endlink                      | Entity Identifier                          |                                                                                                                                                                                                        |
   |![ ](pk.jpg)  | <b>INSTID</b>                         | CHARACTER(64)    | Y         |                                                | Instrument Identifier                      | Unique identifier for an instrument/transaction/account. The name of this column is required to be INSTID by SAS HP Risk.                                                                              |
   |              | WORKGROUP                             | CHARACTER(32)    | N         |                                                | Workgroup                                  | SAS Risk Workgroup. Drives the row-level security                                                                                                                                                      |
   |              | INSTTYPE                              | CHARACTER(32)    | N         |                                                | Instrument Type                            | The instrument type drives mapping to MIP model groups Category                                                                                                                                        |
   |              | PD_SEGMENT_ID                         | CHARACTER(32)    | N         | \link rf_curve.sas \endlink (key: SEGMENT_ID)  | PD Curve Segment Identifier                | Identifier for the PD curve segment. Relevant when CURVE_METHODOLOGY_CD = "PD/LGD"                                                                                                                     |
   |              | LGD_SEGMENT_ID                        | CHARACTER(32)    | N         | \link rf_curve.sas \endlink (key: SEGMENT_ID)  | LGD Curve Segment Identifier               | Identifier for the LGD curve segment. Relevant when CURVE_METHODOLOGY_CD = "PD/LGD"                                                                                                                    |
   |              | LR_SEGMENT_ID                         | CHARACTER(32)    | N         | \link rf_curve.sas \endlink (key: SEGMENT_ID)  | Loss Rate Curve Segment Identifier         | Identifier for the Loss Rate curve segment. Relevant when CURVE_METHODOLOGY_CD = "LR"                                                                                                                  |
   |              | PREPAY_SEGMENT_ID                     | CHARACTER(32)    | N         | \link rf_curve.sas \endlink (key: SEGMENT_ID)  | Pre-Payment Curve Segment Identifier       | Identifier for the Pre-payment curve segment. Relevant when CURVE_METHODOLOGY_CD is not blank                                                                                                          |
   |              | CURVE_METHODOLOGY_CD                  | CHARACTER(32)    | N         |                                                | Curve Methodology Code                     | Controls the type of curves to be used for the calculation of ECL. Valid values: <br> - PD/LGD: PD & LGD curves are used to forecast the expected credit loss <br> - LR: Loss rate curve is used to forecast the expected credit loss |
   |              | PORTFOLIO_SEGMENT                     | CHARACTER(50)    | N         |                                                | Portfolio Segment                          | Please refer to ASU 2016-13, p106.The Portfolio Segment is the level at which an entity develops and documents a systematic methodology                                                                |
   |              | ACCOUNTING_TREATMENT_CD               | CHARACTER(32)    | N         |                                                | Accounting Treatment Code                  | Accounting Treatment also known as Carry Value Code.  Code used to categorize investments that are reported at amortized cost, Held to maturity securities (HTM), versus at fair value, Available for sale securities (AFS) |
   |              | ACCOUNTING_METHOD                     | CHARACTER(14)    | N         |                                                | Accounting Method                          | Accounting Method drives the way entries for the General Ledger are generated                                                                                                                          |
   |              | ASSET_TYPE_DESC                       | CHARACTER(200)   | N         |                                                | Asset Type (Accounting denominations)      | Asset type categorization                                                                                                                                                                              |
   |              | PRODUCT_CD                            | CHARACTER(200)   | N         | \link map_product_hierarchy.sas \endlink       | Product Code                               | Used to lookup the full Product hierarchy.                                                                                                                                                             |
   |              | LOB_ID                                | CHARACTER(64)    | N         | \link map_lob_hierarchy.sas \endlink           | Line of Business Id                        | Used to lookup the full Line of Business hierarchy.                                                                                                                                                    |
   |              | CURRENCY                              | CHARACTER(3)     | N         |                                                | Currency                                   | ISO 3 character currency code                                                                                                                                                                          |
   |              | COUNTERPARTYID                        | CHARACTER(32)    | N         | \link counterparty.sas \endlink                | Counterparty Id                            | Unique Identifier for the Counterparty                                                                                                                                                                 |
   |              | COUNTERPARTYTYPE                      | CHARACTER(100)   | N         |                                                | Counterparty Type                          | Counterparty Type                                                                                                                                                                                      |
   |              | SECTOR_DESC                           | CHARACTER(100)   | N         |                                                | Sector Description                         | Description of the Economic Sector of Activity of the counterparty of the contract (reporting dimension)                                                                                               |
   |              | ORIG_RATING_AGENCY                    | CHARACTER(32)    | N         |                                                | Rating Agency at Origination               | Credit Rating Agency (i.e. FICO, EQUIFAX, S&P)                                                                                                                                                         |
   |              | ORIG_RATING_GRADE                     | CHARACTER(32)    | N         |                                                | Rating Grade/Score at Origination          | Credit Rating Grade/Score. Example: 750 (FICO), AAA (S&P), etc.                                                                                                                                        |
   |              | ORIG_STD_RATING_GRADE                 | CHARACTER(32)    | N         |                                                | Standardised Rading Grade at Origination   | A standardized rating scale level is assigned to each loan (either retail or commercial) so that consistent reporting can be done across the entire portfolio. Mapping is required in order to assign a rating scale level to a given credit score (in case of retail) or rating grade (in case of commercial).<br>Closed List Values:<br> 1 - Largely Risk Free <br> - <i>2 - Minimal Risk</i> <br> - <i>3 - Modest Risk</i> <br> - <i>4 - Bankable</i> <br> - <i>5 - Additional Review</i> <br> - <i>6 - Special Mention</i> <br> - <i>7 - Sub-Standard</i> <br> - <i>8 - Doubtful</i> <br> - <i>9 - Loss</i>  |
   |              | RATING_AGENCY                         | CHARACTER(32)    | N         |                                                | Rating Agency                              | Credit Rating Agency (i.e. FICO, EQUIFAX, S&P)                                                                                                                                                         |
   |              | RATING_GRADE                          | CHARACTER(32)    | N         |                                                | Rating Grade/Score                         | Credit Rating Grade/Score. Example: 750 (FICO), AAA (S&P), etc.                                                                                                                                        |
   |              | STD_RATING_GRADE                      | CHARACTER(32)    | N         |                                                | Standardised Rading Grade                  | A standardized rating scale level is assigned to each loan (either retail or commercial) so that consistent reporting can be done across the entire portfolio. Mapping is required in order to assign a rating scale level to a given credit score (in case of retail) or rating grade (in case of commercial).<br>Closed List Values:<br> 1 - Largely Risk Free <br> - <i>2 - Minimal Risk</i> <br> - <i>3 - Modest Risk</i> <br> - <i>4 - Bankable</i> <br> - <i>5 - Additional Review</i> <br> - <i>6 - Special Mention</i> <br> - <i>7 - Sub-Standard</i> <br> - <i>8 - Doubtful</i> <br> - <i>9 - Loss</i>  |
   |              | ORIG_PIT_PD                           | NUMERIC(8)       | N         |                                                | PIT PD at Origination                      | Point-In-Time Probablilty of Default at origination                                                                                                                                                    |
   |              | TTC_PD                                | NUMERIC(8)       | N         |                                                | TTC PD                                     | Through-The-Cycle Probablilty of Default                                                                                                                                                               |
   |              | PIT_PD                                | NUMERIC(8)       | N         |                                                | PIT PD                                     | Point-In-Time Probablilty of Default                                                                                                                                                                   |
   |              | ORIG_LTV_RT                           | NUMERIC(8)       | N         |                                                | LTV at Origination                         | Loan-To-Value Ratio at origination                                                                                                                                                                     |
   |              | LTV_RT                                | NUMERIC(8)       | N         |                                                | LTV                                        | Loan-To-Value Ratio                                                                                                                                                                                    |
   |              | LGD                                   | NUMERIC(8)       | N         |                                                | LGD                                        | Loss Given Default                                                                                                                                                                                     |
   |              | DOWNTURN_LGD                          | NUMERIC(8)       | N         |                                                | Downturn LGD                               | Downturn Loss Given Default                                                                                                                                                                            |
   |              | ORIGINATION_DT                        | NUMERIC(8)       | N         |                                                | Loan Origination Date                      | Date at which the loan was originated. SAS Date value                                                                                                                                                  |
   |              | SCHEDULE_START_DT                     | NUMERIC(8)       | N         |                                                | Schedule start Date                        | Date at which the repayment schedule starts or started.  SAS Date value                                                                                                                                |
   |              | MATURITY_DT                           | NUMERIC(8)       | N         |                                                | Maturity Date                              | Date at which the loan matures.  SAS Date value                                                                                                                                                        |
   |              | PRINCIPAL_PAYMENT_DT                  | NUMERIC(8)       | N         |                                                | Principal Payment Date                     | Date of the next principal repayment.                                                                                                                                                                  |
   |              | INTEREST_PAYMENT_DT                   | NUMERIC(8)       | N         |                                                | Interest Payment Date                      | Date of the next interest payment                                                                                                                                                                      |
   |              | NEXT_RESET_DT                         | NUMERIC(8)       | N         |                                                | Next Reset Date                            | Date of the next interest fixing                                                                                                                                                                       |
   |              | UNPAID_BALANCE_AMT                    | NUMERIC(8)       | N         |                                                | Unpaid Balance Amount                      |                                                                                                                                                                                                        |
   |              | ORIG_UNPAID_BALANCE_AMT               | NUMERIC(8)       | N         |                                                | Unpaid Balance Amount at Origination       |                                                                                                                                                                                                        |
   |              | CURRENT_RT                            | NUMERIC(8)       | N         |                                                | Current Rate                               | Decimal value                                                                                                                                                                                          |
   |              | EFFECTIVE_INTEREST_RT                 | NUMERIC(8)       | N         |                                                | Effective Interest Rate                    | Decimal value                                                                                                                                                                                          |
   |              | MARGIN_RT                             | NUMERIC(8)       | N         |                                                | Interest Rate Margin                       | Decimal value. Margin over the reference interest rate.                                                                                                                                                |
   |              | INDEX_REFERENCE                       | CHARACTER(16)    | N         |                                                | Interest Rate Reference Curve              | Points to reference curve in scenario data.                                                                                                                                                            |
   |              | PAYMENT_AMT                           | NUMERIC(8)       | N         |                                                | Payment Amount (assumes fixed periodic loan payments (the amount is that associated with a fully drawn credit line))|                                                                                                                               |
   |              | DAYS_PAST_DUE_CNT                     | NUMERIC(8)       | N         |                                                | Days Past Due Count                        | Integer value.                                                                                                                                                                                         |
   |              | MODIFICATION_DT                       | NUMERIC(8)       | N         |                                                | Modification date                          | Date of last modification                                                                                                                                                                              |
   |              | ASSESSMENT_TYPE_CD                    | CHARACTER(10)    | N         |                                                | Assessment type Code                       | Assessment type code: <br> - IA <br> - CA                                                                                                                                                              |
   |              | ASSESSMENT_TYPE_DESC                  | CHARACTER(100)   | N         |                                                | Assessment type Description                | Assessment type description: <br> - Individual Assessment <br> - Collective Assessment                                                                                                                 |
   |              | COLLATERAL_DESC                       | CHARACTER(200)   | N         |                                                | Collateral Type Description                | Drives mapping to hierarchy ecl_collateral_hier                                                                                                                                                        |
   |              | PENDING_OFFER_FLG                     | CHARACTER(3)     | N         |                                                | Pending Offer Flag                         | Indicates that an offer is pending that could be realised in the future  (i.e. currently the pending offer is off-balance until realisation and subsequent drawdown)                                   |
   |              | CUM_WRITE_OFF_AMT                     | NUMERIC(8)       | N         |                                                | (Cumulative) Write-off                     | Drives mapping to worksheets. See \ref p200Other "here" for general worksheet mapping information.       This is the cumulative write-off amount (partial or full)                                     |
   |              | DRAWDOWN_PERIOD_FLG                   | CHARACTER(3)     | N         |                                                | Drawdown Period Flag                       | Indicates that a contract is in its drawdown period allowing additional drawdowns until the full CREDIT_LIMIT_AMT is reached and the OFF_BALANCE_AMT is 0.                                             |
   |              | ISSUED_GUARANTEE_FLG                  | CHARACTER(3)     | N         |                                                | Issued Flag                                | Indicates that a contract is a  pure off balance guarantee issued by the bank that can be called under certain conditions by a beneficiary.                                                            |
   |              | REVOLVING_FLG                         | CHARACTER(3)     | N         |                                                | Revolving Flag                             | Indicates that a contract is revolving, meaning that drawings and repayments don't follow a predefined schedule as long as the CREDIT_LIMIT_AMT is not exceeded.                                       |
   |              | OFF_BALANCE_AMT                       | NUMERIC(8)       | N         |                                                | Off Balance Amount of the Contract         | Indicates amount of contract that is off balance, used for issued guarantees, revolving credits, pending credit offers and term loans in their drawdown period                                         |
   |              | CREDIT_LIMIT_AMT                      | NUMERIC(8)       | N         |                                                | Credit Limit Amount                        | Indicates maximum allowed credit exposure on the contract.                                                                                                                                             |
   |              | DELINQUENCY_FLG                       | CHARACTER(3)     | N         |                                                | Delinquency Flag                           | Indicates delinquency (Y) or not (N)                                                                                                                                                                   |
   |              | MOST_RECENT_DELINQUENCY_DT            | NUMERIC(8)       | N         |                                                | Delinquency Date                           | Date of most recent delinquency                                                                                                                                                                        |
   |              | EVER_DELINQUENT_FLG                   | CHARACTER(32)    | N         |                                                | Ever Delinquent Flag                       | Flag indicating whether there has ever been a delinquency                                                                                                                                              |
   |              | LOAN_STATUS_DESC                      | CHARACTER(32)    | N         |                                                | Loan Status                                | Status of the loan (for instance Impaired/Normal/Special Mention/Pipeline/Written-off...). Used in VA reports                                                                                          |
   |              | GEOGRAPHY_CD                          | CHARACTER(32)    | N         | \link map_geo_hierarchy \endlink               | Geography Code                             | Geography Code (reporting dimension).                                                                                                                                                                  |
   |              | CCF                                   | NUMERIC(8)       | N         |                                                | Credit Conversion Factor                   | Credit Conversion Factor is used to derive an on-balance equivalent for off-balance exposures                                                                                                          |
   |              | INTEREST_RATE_TYPE                    | CHARACTER(8)     | N         |                                                | Type of Interest Rate                      | Type of Interest Rate (see below for detailed values)                                                                                                                                                  |
   |              | INTEREST_PAYMENT_PERIOD_CD            | CHARACTER(16)    | N         |                                                | Interest Payment Periodicity               | Interest payment period(see below for detailed values)                                                                                                                                                 |
   |              | INTEREST_RESET_PERIOD_CD              | CHARACTER(16)    | N         |                                                | Interest Reset Periodicity                 | Interest Reset period. (see below for detailed values)                                                                                                                                                 |
   |              | CAPITAL_PAYMENT_PERIOD_CD             | CHARACTER(16)    | N         |                                                | Capital Payment Periodicity                | Capital Payment Period (see below for detailed values)                                                                                                                                                 |
   |              | PAYMENT_TYPE_CD                       | CHARACTER(16)    | N         |                                                | Type of repayment schedule                 | Type of Repayment Schedule (see below for detailed values)                                                                                                                                             |
   |              | DAY_BASIS_CD                          | CHARACTER(16)    | N         |                                                | Day Basis                                  | Day Count Basis for Interest Accrual Calculation (see below for detailed values)                                                                                                                       |
   |              | POCI_FLG                              | CHARACTER(3)     | N         |                                                | Purchased or Originated Credit-Imparied Assets Flag  |                                                                                                                                                                                              |
   |              | TDR_FLG                               | CHARACTER(3)     | N         |                                                | Troubled Debt Restructuring Flag           |                                                                                                                                                                                                        |
   |              | FORECLOSURE_FLG                       | CHARACTER(3)     | N         |                                                | Foreclosure Flag                           |                                                                                                                                                                                                        |
   |              | RELATED_PARTY_FLG                     | CHARACTER(3)     | N         |                                                | Related Party Flag                         | Identify related parties for disclosure (refer to FAS57)                                                                                                                                               |
   |              | COLLATERAL_SUPPORT_FLG                | CHARACTER(3)     | N         |                                                | Collateral Dependent Flag                  | Identify exposures with collaterals that can serve as alternative means of repayment when the counterparty is experiencing financial difficulties (ASU 2016-13 326-20-50-20)                           |
   |              | FINANCIAL_DIFFICULTIES_FLG            | CHARACTER(3)     | N         |                                                | Financial Difficulties Flag                | Identify counterparties that are experiencing financial difficulties (ASU 2016-13 326-20-50-20)                                                                                                        |
   |              | UNCONDITIONALLY_CANCELABLE_FLG        | CHARACTER(3)     | N         |                                                | Unconditionally Cancelable Flag            |                                                                                                                                                                                                        |
   |              | ACCRUED_INTEREST_AMT                  | NUMERIC(8)       | N         |                                                | Accrued Interest                           |                                                                                                                                                                                                        |
   |              | FEE_AMT                               | NUMERIC(8)       | N         |                                                | Amount of Fees                             |                                                                                                                                                                                                        |
   |              | AMORTIZED_COST_AMT                    | NUMERIC(8)       | N         |                                                | Amortized Cost Basis Amount                | The amount at which an a financing receivable or investment is originated or acquired, adjusted for applicable accrued interest, accretion, or amortization of premium, discount, and net deferred fees or costs, collection of cash, writeoffs, foreign exchange, and fair value hedge accounting adjustments. |
   |              | CUM_RECOVERY_AMT                      | NUMERIC(8)       | N         |                                                | Cumulative Recovery Amount                 | Cumulative amount recovered to date                                                                                                                                                                    |
   |              | NONACCRUAL_STATUS_FLG                 | CHARACTER(3)     | N         |                                                | Nonaccrual Status Flag                     | Indicates nonaccrual status (Y) or not (N)                                                                                                                                                             |
   |              | INTEREST_INCOME_ON_NON_ACC_AMT        | NUMERIC(8)       | N         |                                                | Interest Income Amount on Nonaccrual       | Interest income recognized during the period on nonaccrual assets is reported on nonaccrual disclosure template.                                                                                       |
   |              | COLLATERAL_VALUE_AMT                  | NUMERIC(8)       | N         |                                                | Collateral Value Amount                    | Collaterals are measured at fair value basis.  This amount is reported on collateral-dependent asset disclosure template.                                                                              |
   |              | POCI_PURCHASE_AMT                     | NUMERIC(8)       | N         |                                                | POCI Purchase Amount                       | Purchase price of POCI assets is reported on POCI Reconciliation disclosure template.                                                                                                                  |
   |              | POCI_PAR_AMT                          | NUMERIC(8)       | N         |                                                | POCI Par Value Amount                      | Par Value of POCI assets is reported on POCI Reconciliation disclosure template.                                                                                                                       |
   |              | POCI_PURCHASE_DT                      | NUMERIC(8)       | N         |                                                | POCI Purchase Date                         | Used to determine if a POCI asset was purchased in the current reporting period.                                                                                                                       |
   |              | INIT_ALLOWANCE_AMT                    | NUMERIC(8)       | N         |                                                | Initial Allowance Amount                   | Initial allowance to be used as Previous Period Allowance Amount for the initial run.  Only needs to be populated for the initial run.                                                                 |
   |              | OTHER_ALLOWANCE_AMT                   | NUMERIC(8)       | N         |                                                | Other Allowance Amount                     | Allowance for all other items in the current period                                                                                                                                                    |   
   |              | COLLATERAL_TYPE                       | CHARACTER(100)   | N         |                                                | Collateral Type                            | Type of collateral is reported on the collateral dependent disclosure template.                                                                                                                        |   
   |              | ACQUISITION_DT                        | NUMERIC(8)       | N         |                                                | Acquisition Date                           | Date on which the loan or security was acquired is reported on the POCI Reconciliation disclosure template.                                                                                            |
   |              | FINREP_NON_PERFORMING_FLG             | CHARACTER(1)     | N         |                                                | Finrep - Non-performing indicator          | Drives mapping to FINREP templates                                                                                                                                                                     |
   |              | FINREP_COLLATERAL_TYPE                | CHARACTER(64)    | N         |                                                | Finrep - Collateral Type                   | Drives mapping to FINREP templates                                                                                                                                                                     |
   |              | FINREP_PURPOSE_TYPE                   | CHARACTER(32)    | N         |                                                | Finrep - Purpose Type Code                 | Drives mapping to FINREP templates                                                                                                                                                                     |
   |              | FINREP_PROJECT_FINANCE_FLG            | CHARACTER(1)     | N         |                                                | Finrep - Project Finance indicator         | Accepts either Y (yes) or N (no). Drives mapping to FINREP templates                                                                                                                                   |
   |              | LOW_CREDIT_RISK_FLG                   | CHARACTER(1)     | N         |                                                | Low credit risk flag                       | Accepts either Y (yes) or N (no). Indicates whether the instrument is subject to low credit risk as referred to by IFRS9 B.5.2.22-B.5.2.24. Note that alternatively this flag can be derived in the stage allocation logic.  |
   |              | RANDOMSEED                            | NUMERIC(8)       | N         |                                                | Random Seed Number                         | Random Seed Number used to control and replicate analysis involving random simulations.                                                                                                                |
   |              | EIR_CURVE                             | CHARACTER(32)    | N         | \link rf_curve.sas \endlink (key: SEGMENT_ID)  | Discounting Curve for cashflows Generation | Identifier for the Discounting Curve linked to EIR casfhlows generation. Relevant when CF_DERIVED_EIR_FLG is set to Y.                                                                                 |
   |              | EIR_SPREAD                            | NUMERIC(8)       | N         |                                                | Spread above the EIR_CURVE                 | Spread added to the EIR_CURVE. Relevant when CF_DERIVED_EIR_FLG is set to Y.                                                                                                                           |
   |              | EIR_PRIOR_PAYMENT_DT                  | NUMERIC(8)       | N         |                                                | Prior payment date when computing EIR      | Prior payment date. Relevant when CF_DERIVED_EIR_FLG is set to Y.                                                                                                                                      |
   |              | EIR_RESIDUAL_VALUE_AMT                | NUMERIC(8)       | N         |                                                | Residual Value Amount.                     | Residual Value Amount. Relevant when CF_DERIVED_EIR_FLG is set to Y.                                                                                                                                   |
   |              | CF_DERIVED_EIR_FLG                    | CHARACTER(3)     | N         |                                                | Flag indicating the need to compute EIR    | Flag (Y or N) indicating the need to compute the EIR (Effective Interest Rate) based on cashflows generation.                                                                                          |
   |              | IRRECOVERABLE_FLG                     | CHARACTER(1)     | N         |                                                | Finrep - Irrecoverable contract flag       | Drives mapping to FINREP templates.  Used together with write-off amount to identify amounts to be reported on write-offs.                                                                             |
   |              | MODIFIED_FLG                          | CHARACTER(1)     | N         |                                                | Modification flag                          | Indicates modification of the instrument. Used in FINREP 12.1 report for "Changes due to change in credit risk (net)" and "Changes due to modifications without derecognition (net)"                   |
   
+ Sample values for <b>INTEREST_PAYMENT_PERIOD_CD</b> :
   + 1 MONTH: Interest payment is made monthly
   + 3 MONTH: Interest payment is made quarterly/every 3 months
   + 1 YEAR:  Interest payment is made annually

+ Sample values for <b>INTEREST_RESET_PERIOD_CD</b> :
   + 1 MONTH: Interest rate is reset monthly
   + 3 MONTH: Interest payment is reset quarterly/every 3 months
   + 1 YEAR:  Interest payment is reset annually
   + 5 YEAR:  Interest payment is reset every 5 years

+ Sample values for <b>CAPITAL_PAYMENT_PERIOD_CD</b> :
   + 1 MONTH: Interest payment is made monthly
   + 3 MONTH: Interest payment is made quarterly/every 3 months
   + 6 MONTH: Interest payment is made semi-annually/every 6 months

+ List of values for <b>PAYMENT_TYPE_CD</b> :
   + Level Pay     : Indicating the repayment of principal and interest of a loan at each payment period is a fixed amount
   + Straight Line : Indicating the principal repayment of a loan at each payment period is a fixed amount  
   + Bullet        : Indicating a lump sum of repayment of the principal at the maturity of the loan   
   
+ List of values for <b>DAY_BASIS_CD</b> :
   + 30/360 : Indicating every month has 30 days and each year has 360 days
   + ACT/360: Indicating the actual number of days of a month is used for the month and 360 is used for the number of days in each year
   + ACT/365: Indicating the actual number of days of a month is used for the month and 365 is used for the number of days in each year
   + ACT/ACT: Indicating the actual number of days of a month is used for the month and the actual number of days of a year is used for the year

+ List of values for <b>INTEREST_RATE_TYPE</b> :
   + Fixed    : Indicating interest rate is fixed for the term of the loan
   + Variable : Indicating interest rate is variable for the term of the loan
   + ARM      : Indicating the interest rate of a mortgage loan is adjustable over the term of the loan
   + Hybrid   : Indicating the interest rate of a loan is fixed for a defined period and adjustable for the rest of the loan term

   \ingroup ddlFactCreditRisk
   \author  SAS Institute Inc.
   \date    2018
*/
   
CREATE TABLE &LIBREF..CREDIT_PORTFOLIO (
   REPORTING_DT                     DATE           label = 'Reporting Date'         FORMAT = &DTFMT.,
   ENTITY_ID                        VARCHAR(32)    label = 'Entity ID',
   INSTID                           VARCHAR(64)    label = 'Instrument Identifier',
   WORKGROUP                        VARCHAR(32)    label = 'Workgroup',
   INSTTYPE                         VARCHAR(32)    label = 'Instrument Type',
   PD_SEGMENT_ID                    VARCHAR(32)    label = 'PD Segment Identifier',
   LGD_SEGMENT_ID                   VARCHAR(32)    label = 'LGD Segment Identifier',
   LR_SEGMENT_ID                    VARCHAR(32)    label = 'Loss Rate Segment Identifier',
   PREPAY_SEGMENT_ID                VARCHAR(32)    label = 'Pre-Payment Segment Identifier',
   CURVE_METHODOLOGY_CD             VARCHAR(32)    label = 'Curve Methodology Code',
   PORTFOLIO_SEGMENT                VARCHAR(50)    label = 'Portfolio Segment',
   ACCOUNTING_TREATMENT_CD          VARCHAR(32)    label = 'Accounting Treatment Code',
   ACCOUNTING_METHOD                VARCHAR(14)    label = 'Accounting Method',
   ASSET_TYPE_DESC                  VARCHAR(200)   label = 'Asset Type',
   PRODUCT_CD                       VARCHAR(100)   label = 'Product Code',
   LOB_ID                           VARCHAR(100)   label = 'Line of Business Id',
   CURRENCY                         VARCHAR(3)     label = 'Currency',
   COUNTERPARTYID                   VARCHAR(32)    label = 'Counterparty Id',
   COUNTERPARTYTYPE                 VARCHAR(100)   label = 'Counterparty Type',
   SECTOR_DESC                      VARCHAR(100)   label = 'Sector Description',
   ORIG_RATING_AGENCY               VARCHAR(32)    label = 'Rating Agency at Origination',
   ORIG_RATING_GRADE                VARCHAR(32)    label = 'Rating Grade at Origination',
   ORIG_STD_RATING_GRADE            VARCHAR(32)    label = 'Standardised Rating Grade at Origination',
   RATING_AGENCY                    VARCHAR(32)    label = 'Rating Agency',
   RATING_GRADE                     VARCHAR(32)    label = 'Rating Grade',
   STD_RATING_GRADE                 VARCHAR(32)    label = 'Standardised Rating Grade',
   ORIG_PIT_PD                      NUMERIC(8)     label = 'PIT PD at Origination',
   TTC_PD                           NUMERIC(8)     label = 'TTC PD',
   PIT_PD                           NUMERIC(8)     label = 'PIT PD',
   ORIG_LTV_RT                      NUMERIC(8)     label = 'LTV at Origination',
   LTV_RT                           NUMERIC(8)     label = 'LTV',
   LGD                              NUMERIC(8)     label = 'LGD',
   DOWNTURN_LGD                     NUMERIC(8)     label = 'Downturn LGD',
   ORIGINATION_DT                   DATE           label = 'Origination Date'       FORMAT = &DTFMT.,
   SCHEDULE_START_DT                DATE           label = 'Schedule Start Date'    FORMAT = &DTFMT.,
   MATURITY_DT                      DATE           label = 'Maturity Date'          FORMAT = &DTFMT.,
   PRINCIPAL_PAYMENT_DT             DATE           label = 'Principal Payment Date' FORMAT = &DTFMT.,
   INTEREST_PAYMENT_DT              DATE           label = 'Interest Payment Date'  FORMAT = &DTFMT.,
   NEXT_RESET_DT                    DATE           label = 'Next Reset Date'        FORMAT = &DTFMT.,
   UNPAID_BALANCE_AMT               NUMERIC(8)     label = 'Unpaid Balance Amount',
   ORIG_UNPAID_BALANCE_AMT          NUMERIC(8)     label = 'Unpaid Balance Amount at Origination',
   CURRENT_RT                       NUMERIC(8)     label = 'Current Contractual Interest Rate',
   EFFECTIVE_INTEREST_RT            NUMERIC(8)     label = 'Effective Interest Rate',
   MARGIN_RT                        NUMERIC(8)     label = 'Interest Rate Margin',
   PAYMENT_AMT                      NUMERIC(8)     label = 'Payment Amount',
   DAYS_PAST_DUE_CNT                NUMERIC(8)     label = 'Days Past Due',
   MODIFICATION_DT                  DATE           label = 'Modification Date'      FORMAT = &DTFMT.,
   ASSESSMENT_TYPE_CD               VARCHAR(10)    label = 'Assessment Type Code',
   ASSESSMENT_TYPE_DESC             VARCHAR(100)   label = 'Assessment Type Description',
   COLLATERAL_DESC                  VARCHAR(200)   label = 'Collateral Description',
   CUM_WRITE_OFF_AMT                NUMERIC(8)     label = 'Write-off Amount',
   PENDING_OFFER_FLG                VARCHAR(3)     label = 'Pending Offer Flag',
   DRAWDOWN_PERIOD_FLG              VARCHAR(3)     label = 'Drawdown Period Flag',
   ISSUED_GUARANTEE_FLG             VARCHAR(3)     label = 'Issued Guarantee Flag',
   REVOLVING_FLG                    VARCHAR(3)     label = 'Revolving Flag',
   OFF_BALANCE_AMT                  NUMERIC(8)     label = 'Off-Balance Amount',
   CREDIT_LIMIT_AMT                 NUMERIC(8)     label = 'Credit Limit Amount',
   DELINQUENCY_FLG                  VARCHAR(3)     label = 'Delinquency Flag',
   MOST_RECENT_DELINQUENCY_DT       DATE           label = 'Most Recent Delinquency Date'   FORMAT = &DTFMT.,
   EVER_DELINQUENT_FLG              VARCHAR(3)     label = 'Ever Delinquent Flag',
   LOAN_STATUS_DESC                 VARCHAR(32)    label = 'Loan Status',
   GEOGRAPHY_CD                     VARCHAR(32)    label = 'Geography Code',
   CCF                              NUMERIC(8)     label = 'Credit Conversion Factor',
   INTEREST_RATE_TYPE               VARCHAR(8)     label = 'Interest Rate Type',
   INDEX_REFERENCE                  VARCHAR(16)    label = 'Interest Rate Reference Curve',
   INTEREST_PAYMENT_PERIOD_CD       VARCHAR(16)    label = 'Interest Payment Period Code',
   INTEREST_RESET_PERIOD_CD         VARCHAR(16)    label = 'Interest Reset Period Code',
   CAPITAL_PAYMENT_PERIOD_CD        VARCHAR(16)    label = 'Capital Payment Period Code',
   PAYMENT_TYPE_CD                  VARCHAR(16)    label = 'Type of Repayment Schedule',
   DAY_BASIS_CD                     VARCHAR(16)    label = 'Day Basis',
   POCI_FLG                         VARCHAR(3)     label = 'Purchased Credit Deteriorated Flag',
   TDR_FLG                          VARCHAR(3)     label = 'Troubled Debt Restructuring Flag',
   FORECLOSURE_FLG                  VARCHAR(3)     label = 'Foreclosure Flag',
   RELATED_PARTY_FLG                VARCHAR(3)     label = 'Related Party Flag',
   COLLATERAL_SUPPORT_FLG           VARCHAR(3)     label = 'Collateral Support Flag',
   FINANCIAL_DIFFICULTIES_FLG       VARCHAR(3)     label = 'Financial Difficulties Flag',
   UNCONDITIONALLY_CANCELABLE_FLG   VARCHAR(3)     label = 'Unconditionally Cancelable Flag',
   ACCRUED_INTEREST_AMT             NUMERIC(8)     label = 'Accrued Interest',
   FEE_AMT                          NUMERIC(8)     label = 'Amount of Fees', 
   AMORTIZED_COST_AMT               NUMERIC(8)     label = 'Amortized Cost Basis Amount',
   CUM_RECOVERY_AMT                 NUMERIC(8)     label = 'Cumulative Recovery Amount',
   NONACCRUAL_STATUS_FLG            VARCHAR(3)     label = 'Nonaccrual Status Flag',
   INTEREST_INCOME_ON_NON_ACC_AMT   NUMERIC(8)     label = 'Interest Income on Non Accrual Amount',
   COLLATERAL_VALUE_AMT             NUMERIC(8)     label = 'Collateral Value Amount',
   POCI_PURCHASE_AMT                NUMERIC(8)     label = 'POCI Purchase Amount',
   POCI_PAR_AMT                     NUMERIC(8)     label = 'POCI Par Value Amount',
   POCI_PURCHASE_DT                 DATE           label = 'POCI Purchase Date'   FORMAT = &DTFMT.,
   INIT_ALLOWANCE_AMT               NUMERIC(8)     label = 'Initial Allowance Amount',
   OTHER_ALLOWANCE_AMT              NUMERIC(8)     label = 'Other Allowance Amount', 
   COLLATERAL_TYPE                  VARCHAR(100)   label = 'Collateral Type',
   ACQUISITION_DT                   NUMERIC(8)     label = 'Acquisition Date' FORMAT = &DTFMT.,
   FINREP_NON_PERFORMING_FLG        VARCHAR(1)     label = 'Finrep - Non-performing indicator',
   FINREP_COLLATERAL_TYPE           VARCHAR(64)    label = 'Finrep - Collateral Type',
   FINREP_PURPOSE_TYPE              VARCHAR(32)    label = 'Finrep - Purpose Type',
   FINREP_PROJECT_FINANCE_FLG       VARCHAR(1)     label = 'Finrep - Project Finance indicator',
   LOW_CREDIT_RISK_FLG              VARCHAR(1)     label = 'Low Credit Risk Flag',
   RANDOMSEED                       NUMERIC(8)     label = 'Random Seed Number',
   EIR_CURVE                        VARCHAR(32)    label = 'Discounting Curve for cashflows Generation',
   EIR_SPREAD                       NUMERIC(8)     label = 'Spread above the EIR_CURVE',
   EIR_PRIOR_PAYMENT_DT             NUMERIC(8)     label = 'Prior payment date when computing EIR' FORMAT = &DTFMT.,
   EIR_RESIDUAL_VALUE_AMT           NUMERIC(8)     label = 'Residual Value Amount',
   CF_DERIVED_EIR_FLG               VARCHAR(3)     label = 'Flag indicating the need to compute EIR',
   IRRECOVERABLE_FLG                VARCHAR(1)     label = 'Finrep - Irrecoverable contract flag',
   MODIFIED_FLG                     VARCHAR(1)     label = 'Modification Flag',
   CONSTRAINT PRIM_KEY PRIMARY KEY (REPORTING_DT, ENTITY_ID, INSTID)
);
